services:
  db:
    image: 'postgres:13-alpine'
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: desafio
      POSTGRES_PASSWORD: user123
      POSTGRES_USER: user
    restart: always
    networks:
      - desafio-network
  
  pgadmin:
    image: dpage/pgadmin4:8.11.0
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@user.com
      PGADMIN_DEFAULT_PASSWORD: secret
    depends_on:
      - db
    networks:
      - desafio-network

  desafio:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/desafio
      SPRING.DATASOURCE.USERNAME: user
      SPRING.DATASOURCE.PASSWORD: user123
    command:
      - mvn spring-boot:run
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db
    networks:
      - desafio-network

networks:
  desafio-network:
    driver: bridge